name: run2

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 10 17 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run main
        env:
          GLADOS: koa:sess=eyJ1c2VySWQiOjIyNTUyMCwiX2V4cGlyZSI6MTcxNjcyOTQxMTY2OCwiX21heEFnZSI6MjU5MjAwMDAwMDB9; koa:sess.sig=WKHmrfSK8h4xz6jciaAxJUH7gcI; _gid=GA1.2.354640511.1702882612; _gat_gtag_UA_104464600_2=1; _ga=GA1.2.278168827.1690092687; _ga_CZFVKMNT9J=GS1.1.1702882611.5.1.1702882628.0.0.0
          NOTIFY: 829ff772781249aa970d94cc63602e86
